Modify keypress navigation to only work when focus is on body or html element.
This is to allow presentations to have, for example, form elements, where
users can type text, including spaces, use arrows, etc.

Exception: TAB will always cause navigation to next step.

Adds new Form plugin, which blurs() focus on impress:stepleave. This is to
prevent an input field from being focused when it is no longer visible.